name: ci

on:
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends libcmocka-dev
      - name: Build library
        run: make -j4
      - name: Build test programs
        run: make testprogs
      - name: Run unit tests
        run: make unittest
      - name: Run ASAN tests
        run: make addrtest
      - name: Run MSAN tests
        run: make memtest
      - name: Run UBSAN tests
        run: make ubtest
      - name: Run tests without FPU (no float)
        run: make nofloattest
