name: ci

on:
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends libcmocka-dev
      - name: Compile as C++
        run: g++ -fsyntax-only -xc++ cmp.c
      - name: Build library
        run: make -j4
      - name: Build test programs
        run: make testprogs
      - name: Run tests
        run: make test
      - name: Compile as C++
        run: g++ -fsyntax-only -xc++ cmp.c
